version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: peerchat-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - peerchat-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: peerchat-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - peerchat-network
    restart: unless-stopped

networks:
  peerchat-network:
    driver: bridge