# Dockerfile.backend

FROM node:16-alpine

# Set working directory
WORKDIR /usr/src/app/backend

# Copy backend package.json and package-lock.json
COPY backend/package*.json ./

# Install backend dependencies
RUN npm install

RUN npm install -g express

RUN npm install -g dotenv

RUN npm install -g cors

# Copy backend source code
COPY backend/ .

# Expose backend port
EXPOSE 3000

# Start the backend server using Node.js directly
CMD ["node", "server.js"]