# Dockerfile.backend

FROM node:16-alpine

# Set working directory
WORKDIR /usr/src/app/backend

# Copy backend package.json and package-lock.json
COPY backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY backend/ .

# Install PM2 globally
RUN npm install -g pm2

# Expose backend port
EXPOSE 3000

# Start the backend server with PM2 Runtime
CMD ["pm2-runtime", "server.js", "--name", "backend"]